### ISSUE TITLE
Move FileService API over to core (without Angular 2 stuff)

### ISSUE THREAD

**Issue by slaymaker1907** [2graphic/sinap-core#14]
This way we can have a platform independent way for doing all this stuff, including plugin loading.

**Comment by slaymaker1907** [comment]
@Sheyne is there a way to do create compiler hosts asynchronously? My concern is less about performance and more about keeping the FileService API simple.

**Comment by Sheyne** [comment]
You can keep the file loader async, then do a Promise.all on all the files. Compiler hosts need to have strings, not promises of strings. Keep primitive file loading just for the typescript library files (which we won't bundle for anything but dev builds anyway). The lib.*.d.ts files weigh about 50mb, so it's not worth adding to the release target, we can just ignore that subset of errors when loading plugins on a release build (dev builds shouldn't ignore).
