### ISSUE TITLE
Typescript Reference Path Messed Up

### ISSUE THREAD

**Issue by slaymaker1907** [2graphic/sinap-core#15]
This is from the test folder. What needs to be set up for this to work? This directory does not exist on my machine even after an npm install.

```typescript
/// <reference path="../typings/globals/mocha/index.d.ts" />
```

**Comment by slaymaker1907** [comment]
It looks like this is because you have to run typings. Should we include typings as a dependency and then put typings in the install script?

**Comment by Sheyne** [comment]
Like npm, typings is supposed to just be installed globally.

**Comment by Sheyne** [comment]
I suppose we could add as a dev dependency and put in the install script, but this seems like this isn't common practice. @RighteousRaichu @ilargierdi thoughts?

**Comment by cj-dimaano** [comment]
I think it would be fine to include it as a dev dependency.

**Comment by danielscottjames** [comment]
Include as dev dependency.
