### ISSUE TITLE
Graphs Should Be Easy to Create Programatically

### ISSUE THREAD

**Issue by slaymaker1907** [2graphic/sinap-core#28]
Right now, it is very verbose and difficult to create graphs programatically for testing. We should implement an easy to use API for creating plugin graphs similar to how it is easy to read these graphs inside of interpreters.

**Comment by Sheyne** [comment]
Consider #61 and https://github.com/2graphic/sinap-core/blob/e80b5fa14f9925ec9346184d6eb8501685db83cd/test/test-interpreters.ts#L1320-L1351
