### ISSUE TITLE
Value objects.

### ISSUE THREAD

**Issue by danielscottjames** [2graphic/sinap-core#31]
Preferably whenever sinap-core passes a value to the IDE, the value should be wrapped up in its type information.

Something like: 
```
Value {
  type: Type;
  value: any;
}
```

This will be the easiest way to use these value wherever they need to be used inside the IDE. Related to 2graphic/sinap-ide#59

**Comment by danielscottjames** [comment]
@Sheyne check this out and see what you think: 2graphic/sinap-ide@af45152

**Comment by Sheyne** [comment]
Is it a big deal if the interface is 
```ts
Value {
  type: Type;
  data: any;
}
```

I made CoreElement also be a CoreValue, and it calls it's `value` field `data`. If you want I can refactor both to be called value.

**Comment by danielscottjames** [comment]
Notes from yesterday and this morning:

* Program should return error as result and any partial states[] it has (never throw an error.)
  * addressed
* Error should be a type
  * addressed
* **CoreValue change detection**
* PluginTypeEnvironment on CoreValue or Type
  * addressed
* Program expose its plugin.
  * addressed
* Plugin returning “FakeUnionType” instead of boolean. FakeUnionType doesn’t have an env
  * addressed
* Program.validate() returns <strike>“TypeError: Cannot read property 'length' of undefined”</strike> empty array, running program works. We should change it to just return a string. (Or corevalue of Error type)
* Be able to create Object Types.
  * addressed
* ObjectType has “__constructor” member?
  * addressed
* **Method to get a member from ObjectType as CoreValue**
  * in progress
* **Default values for CoreValue's**
* Include missing file in sinap-core
  * addressed

I figured out what was causing the Changes during change detection if you’re interested I can tell you later.

**Comment by danielscottjames** [comment]
"TypeError: Cannot read property 'intrinsicName' of undefined
    at FakeUnionType.isAssignableTo"
