### ISSUE TITLE
Can Not Run Tests on Windows

### ISSUE THREAD

**Issue by slaymaker1907** [2graphic/sinap-core#33]
It looks like it is doing some bash command thing.

**Comment by slaymaker1907** [comment]
@Sheyne please make sure to do things in a platform agnostic way.

**Comment by Sheyne** [comment]
Does `npm test` run?

**Comment by Sheyne** [comment]
Oh. The environment variable check. Will you make that platform agnostic?

**Comment by slaymaker1907** [comment]
Yep, I made a branch to fix it.
