### ISSUE TITLE
Setup loading of plugins

### ISSUE THREAD

**Issue by Sheyne** [2graphic/sinap-core#5]
Use a plugin.json file:

```json
{
    "kind": ["Formal Langauges", "DFA"],
    "description": "Implements loading and interpreting deterministic finite state automata",
    "version": "1.0.0",
    "plugin-file": "plugin.ts"
}
```

**Comment by slaymaker1907** [comment]
I think instead of that I'm going to use a package.json as we talked about on Friday. The special stuff we need will be done by a custom object in the package.json.

```json
{
    "description": "Implements loading and interpreting deterministic finite state automata",
    "version": "1.0.0",
    "sinap": {
        "kind": ["Formal Langauges", "DFA"],
        "plugin-file": "plugin.ts"
    }
}
```
The advantage of this approach is that we will be able to install dependencies of plugins easily. We can do this relatively securely through the --ignore-scripts option of npm install.

**Comment by slaymaker1907** [comment]
The only thing I'm not entirely sure of is the best way to support collections of plugins. I'm thinking we just expect them to be installed on npm and somehow manage them that way. I also think that if we allow for installing through npm, it may be easy enough to install stuff that we don't need lists of plugins.

**Comment by danielscottjames** [comment]
Regardless of how it gets done, I think a feature we definitely need to support is the end user only entering one URL to install all of the FLAP plugins.

**Comment by slaymaker1907** [comment]
This is mostly implemented on my branch as far as code. I am currently updating tests to use the new API (which will undoubtedly uncover bugs in my implementation).

**Comment by slaymaker1907** [comment]
Closing this issue since it is now merged into core, though IDE needs to be updated still.
