### ISSUE TITLE
BFS.types.result should instanceof Union<Array<Node>>

### ISSUE THREAD

**Issue by Sheyne** [2graphic/sinap-core#94]

**Comment by danielscottjames** [comment]
Should `instanceof` just `Array<Node>`?

**Comment by Sheyne** [comment]
Isn't plugin.types.result always a union, even if there's only one option?

**Comment by danielscottjames** [comment]
No, the other plugins are just a string, I think we decided if there's just one option then to strip the type out of the union.

**Comment by danielscottjames** [comment]
Otherwise the IDE won't know if it's supposed to be a real Union or not.

**Comment by Sheyne** [comment]
Good point.
