### ISSUE TITLE
Constraints aren't being properly checked for node/edge types

### ISSUE THREAD

**Issue by slaymaker1907** [2graphic/sinap-core#97]
Need to check edges for source/destination types and nodes for parents/children to make sure that things can be associated with each other.

I ran into this when making an ER diagram plugin since it has pretty specific type constraints about what kind of nodes can be associated with what.

**Comment by danielscottjames** [comment]
Might be fixed in my branch.

**Comment by slaymaker1907** [comment]
This is a result of not using the last parameter in validateEdge within the IDE.

On a related note, I think we ought to change validateEdge to take an element type rather than an element value for the edge.

What do you think, @Sheyne?

**Comment by Sheyne** [comment]
Should remain an ElementValue so that custom plugin validateEdge implementations can look at the details of the edge.

**Comment by slaymaker1907** [comment]
I've been playing around with this some more and I believe that there is a catastrophic bug in the way that the main issue is that type checks are not being performed correctly when the type of children or parents is a Union type.

**Comment by slaymaker1907** [comment]
I have added a test for this on the validate-edge branch.

**Comment by slaymaker1907** [comment]
Problem was with IDE.
